### Variables
@baseUrl = http://localhost:8080
@contentType = application/json
@adminId = 8d77f322-3161-4994-8b12-2d2e0584a7f4
@annaId = bb3c530f-00a6-4a6d-b2e8-bc1fa8a1ac5d

### Erase user
DELETE http://localhost:8080/api/users/eraseUser/user
Authorization: Bearer {{auth_token}}

### Register
POST http://localhost:8080/api/auth/register
Content-Type: {{contentType}}

{
  "login": "user",
  "password": "user"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: {{contentType}}

#{
#  "login": "admin",
#  "password": "admin"
#}

{
  "login": "anna",
  "password": "anna"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Check role
GET http://localhost:8080/api/users/checkRole
Authorization: Bearer {{auth_token}}

### Show all users (ADMIN)
GET http://localhost:8080/api/users/allUsers
Authorization: Bearer {{auth_token}}

### Delete user (ADMIN)
DELETE http://localhost:8080/api/users/delete/{{annaId}}
Authorization: Bearer {{auth_token}}

### Unban user (ADMIN)
POST http://localhost:8080/api/users/{{annaId}}/unban
Authorization: Bearer {{auth_token}}

### Add role (ADMIN)
POST http://localhost:8080/api/users/{{annaId}}/roles/add?
    roleName=ROLE_USER
Authorization: Bearer {{auth_token}}

### Remove role (ADMIN)
POST {{baseUrl}}/api/users/{{annaId}}/roles/remove?
    roleName=ROLE_USER
Authorization: Bearer {{auth_token}}

### Show all books
GET http://localhost:8080/api/books/allBooks
Authorization: Bearer {{auth_token}}

### Show all available (active) books
GET http://localhost:8080/api/books/allAvailableBooks
Authorization: Bearer {{auth_token}}

### Check if concrete book is available
GET http://localhost:8080/api/books/isBookAvailable/4b02fe60-1b83-4905-80e1-40b811653622
Authorization: Bearer {{auth_token}}

### List information about concrete book
GET http://localhost:8080/api/books/findBookById/4b02fe60-1b83-4905-80e1-40b811653622
Authorization: Bearer {{auth_token}}

### Add new book
POST http://localhost:8080/api/books
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "",
  "title": "Quo Vadis",
  "author": "Henryk Sienkiewicz",
  "price": 120,
  "isActive": true
}

### Delete book (soft delete)
DELETE http://localhost:8080/api/books/e3087b1c-7621-4a6d-a4e3-b205e5c057cb
Authorization: Bearer {{auth_token}}

### Erase book
DELETE http://localhost:8080/api/books/erase/3f956998-4f34-48cc-a038-dd8a79b7e2dd
Authorization: Bearer {{auth_token}}

### Viev my cart
GET http://localhost:8080/api/cart/view
Authorization: Bearer {{auth_token}}

### Add item to my cart
POST http://localhost:8080/api/cart/add?
    bookId=e3087b1c-7621-4a6d-a4e3-b205e5c057cb
Authorization: Bearer {{auth_token}}

### Delete item from my cart
DELETE http://localhost:8080/api/cart/delete/2a3ecec9-a966-4886-8613-f9ac9cc835bf
Authorization: Bearer {{auth_token}}

### Clear my cart
DELETE http://localhost:8080/api/cart/clear
Authorization: Bearer {{auth_token}}

### Place order
POST http://localhost:8080/api/orders/placeOrder
Authorization: Bearer {{auth_token}}

### Checkout
POST http://localhost:8080/api/orders/checkout/6192939f-544c-4b4a-bcf5-4b670f55ac47
Authorization: Bearer {{auth_token}}

### Status change (PAID, SHIPPED, DELIVERED)
POST http://localhost:8080/api/orders/changeStatus/c50b2ac9-94e7-4c9a-9be3-964a8ee3623d?
    orderStatus=DELIVERED
Authorization: Bearer {{auth_token}}