### Variables
@baseUrl = http://localhost:8080
@contentType = application/json
@adminId = 8d77f322-3161-4994-8b12-2d2e0584a7f4
@annaId = bb3c530f-00a6-4a6d-b2e8-bc1fa8a1ac5d

### Erase user
DELETE http://localhost:8080/api/users/eraseUser/user
Authorization: Bearer {{auth_token}}

### Register
POST http://localhost:8080/api/auth/register
Content-Type: {{contentType}}

{
  "login": "user",
  "password": "user"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: {{contentType}}

{
  "login": "admin",
  "password": "admin"
}

#{
#  "login": "anna",
#  "password": "anna"
#}

#{
#  "login": "user",
#  "password": "user"
#}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Check role
GET http://localhost:8080/api/users/checkRole
Authorization: Bearer {{auth_token}}

### Show all users (ADMIN)
GET http://localhost:8080/api/users/allUsers
Authorization: Bearer {{auth_token}}

### Delete user (ADMIN)
DELETE http://localhost:8080/api/users/delete/{{annaId}}
Authorization: Bearer {{auth_token}}

### Unban user (ADMIN)
POST http://localhost:8080/api/users/{{annaId}}/unban
Authorization: Bearer {{auth_token}}

### Add role (ADMIN)
POST http://localhost:8080/api/users/{{annaId}}/roles/add?
    roleName=ROLE_USER
Authorization: Bearer {{auth_token}}

### Remove role (ADMIN)
POST {{baseUrl}}/api/users/{{annaId}}/roles/remove?
    roleName=ROLE_USER
Authorization: Bearer {{auth_token}}

### Show all books
GET http://localhost:8080/api/books/allBooks
Authorization: Bearer {{auth_token}}

### Show all available (active) books
GET http://localhost:8080/api/books/allAvailableBooks
Authorization: Bearer {{auth_token}}

### Check if concrete book is available
GET http://localhost:8080/api/books/isBookAvailable/7f89cdd1-9ad6-4149-af36-117c96ef3ae2
Authorization: Bearer {{auth_token}}

### List information about concrete book
GET http://localhost:8080/api/books/findBookById/7f89cdd1-9ad6-4149-af36-117c96ef3ae2
Authorization: Bearer {{auth_token}}

### Add new book
POST http://localhost:8080/api/books
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "",
  "title": "Dziady",
  "author": "Adam Mickiewicz",
  "price": 99,
  "isActive": true
}

### Delete book
DELETE http://localhost:8080/api/books/e0b72dfd-152d-4858-92fa-db5dd1e7870a
Authorization: Bearer {{auth_token}}

### Erase book
DELETE http://localhost:8080/api/books/erase/f240c825-2fb5-429b-ab1c-b1181f446baa
Authorization: Bearer {{auth_token}}

### Viev my cart
GET http://localhost:8080/api/cart/view
Authorization: Bearer {{auth_token}}

### Add item to my cart
POST http://localhost:8080/api/cart/add?
    bookId=f240c825-2fb5-429b-ab1c-b1181f446baa
Authorization: Bearer {{auth_token}}

### Delete item from my cart
DELETE http://localhost:8080/api/cart/delete/d676ebf2-2831-4b18-a290-46fb2a3e0253
Authorization: Bearer {{auth_token}}

### Clear my cart
DELETE http://localhost:8080/api/cart/clear
Authorization: Bearer {{auth_token}}

### Place order
POST http://localhost:8080/api/orders/placeOrder
Authorization: Bearer {{auth_token}}

### Checkout
POST http://localhost:8080/api/orders/checkout/915e9a5f-ec9a-4cf5-9006-d4274655ca33
Authorization: Bearer {{auth_token}}

### Status change (PAID, SHIPPED, DELIVERED)
POST http://localhost:8080/api/orders/changeStatus/b77cf03f-edbe-4700-a19e-c6c07cbd28c4?
    orderStatus=DELIVERED
Authorization: Bearer {{auth_token}}