### Variables
@baseUrl = http://localhost:8080
@contentType = application/json
@adminId = fc6e600b-e89e-42e2-b2b7-ca18edb68924
@grzesioId = 785b5d07-3afc-4928-8ec2-d7befc9ae958
@user1Id = 02068dbc-e256-4174-acd8-7f2f6aa8102e

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "login": "admin",
  "password": "admin"
}

> {%
    client.global.set("auth_token", response.body.token);
%}


### Register
POST {{baseUrl}}/api/auth/register
Content-Type: {{contentType}}

{
  "login": "",
  "password": ""
}

### Get all rentals (ADMIN)
GET {{baseUrl}}/api/rentals/all
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Get all active rentals (ADMIN)
GET {{baseUrl}}/api/rentals/allActive
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Get my active rentals (USER, ADMIN)
GET {{baseUrl}}/api/rentals/getRented
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Rent (USER, ADMIN)
POST {{baseUrl}}/api/rentals/rent
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "vehicleId": "1"
}

### Return (USER, ADMIN)
POST {{baseUrl}}/api/rentals/return
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
"vehicleId": "1"
}

### Get all users (ADMIN)
GET {{baseUrl}}/api/users/allUsers
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Add role (ADMIN)
POST {{baseUrl}}/api/users/{{user1Id}}/roles/add?
    roleName=ROLE_ADMIN
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Remove role (ADMIN)
POST {{baseUrl}}/api/users/{{user1Id}}/roles/remove?
    roleName=ROLE_ADMIN
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Get all vehicles (ADMIN)
GET {{baseUrl}}/api/vehicles/all
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Get vehicle by id (ADMIN)
GET {{baseUrl}}/api/vehicles/1
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Get available vehicles (USER, ADMIN)
GET {{baseUrl}}/api/vehicles/allActive
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Get user roles (USER, ADMIN)
GET {{baseUrl}}/api/users/checkRole
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

### Delete USER (ADMIN)
DELETE {{baseUrl}}/api/users/delete/{{user1Id}}
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}